class Piqley < Formula
  desc "Plugin-driven photographer workflow engine"
  homepage "https://github.com/josephquigley/piqley"
  license "MIT"

  # Uncomment and update for tagged releases:
  # url "https://github.com/josephquigley/piqley/archive/refs/tags/v1.0.0.tar.gz"
  # sha256 "..."
  #
  # bottle do
  #   root_url "https://github.com/josephquigley/piqley/releases/download/v1.0.0"
  #   sha256 cellar: :any_skip_relocation, arm64_sequoia: "..."
  # end

  # Local development — switch to GitHub URL when published:
  # head "https://github.com/josephquigley/piqley.git", branch: "main"
  head "file:///Users/wash/Developer/tools/quigsphoto-uploader", using: :git, branch: "main"

  depends_on xcode: ["26.0", :build]
  depends_on :macos
  depends_on "gnupg"

  def install
    system "swift", "build",
           "-c", "release",
           "--disable-sandbox",
           "--scratch-path", buildpath/".build"
    bin.install buildpath/".build/release/piqley"
    man1.install "man/piqley.1"

    # Shell completions generated by swift-argument-parser
    generate_completions_from_executable(bin/"piqley", "--generate-completion-script")
  end

  test do
    assert_match "Plugin-driven photographer workflow engine", shell_output("#{bin}/piqley --help")
  end
end
